apiVersion: apps/v1
kind: Deployment
metadata:
  name: skillexchange-app
  labels:
    app: skillexchange-app
    version: v1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: skillexchange-app
  template:
    metadata:
      labels:
        app: skillexchange-app
        version: v1
    spec:
      containers:
      - name: skillexchange-app
        image: hardikmaheshwari/skillexchange-app:latest
        ports:
        - containerPort: 3000
          name: http
          protocol: TCP
        
        envFrom:
        - configMapRef:
            name: skillexchange-app-config
        - secretRef:
            name: skillexchange-app-secret
        
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 10
          successThreshold: 1
          failureThreshold: 3
        
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 15
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        
        volumeMounts:
        - name: app-uploads
          mountPath: /app/public/uploads
        - name: app-logs
          mountPath: /app/logs
        
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          runAsUser: 1000
          readOnlyRootFilesystem: false
          capabilities:
            drop:
            - ALL
            add:
            - NET_BIND_SERVICE
      
      volumes:
      - name: app-uploads
        hostPath:
          path: /opt/skillexchange-app/uploads
          type: DirectoryOrCreate
      - name: app-logs
        hostPath:
          path: /opt/skillexchange-app/logs
          type: DirectoryOrCreate
      
      securityContext:
        fsGroup: 1000
      
      restartPolicy: Always
      dnsPolicy: ClusterFirst

---
# Horizontal Pod Autoscaler
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: skillexchange-app-hpa
  labels:
    app: skillexchange-app
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: skillexchange-app
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 50
        periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 100
        periodSeconds: 30
