apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
  namespace: skillexchange
spec:
  serviceName: "mongodb"
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo:6.0
        ports:
        - containerPort: 27017
          name: mongo
        volumeMounts:
        - name: mongodb-data
          mountPath: /data/db
      volumes:
      - name: mongodb-data
        hostPath:
          path: /mnt/data/mongodb   # This path will be created on the node
          type: DirectoryOrCreate
